import 'package:flutter/material.dart';

const expensesCategories = [
  {
    "uuid": "dfe-1",
    "icon": Icons.shopping_cart_outlined,
    "type": "expense",
    "name": "Alimentos",
    "color": Colors.red,
  },
  {
    "uuid": "dfe-2",
    "icon": Icons.health_and_safety_outlined,
    "type": "expense",
    "name": "Salud",
    "color": Colors.red,
  },
  {
    "uuid": "dfe-3",
    "icon": Icons.home_outlined,
    "type": "expense",
    "name": "Vivienda",
    "color": Colors.red,
  },
  {
    "uuid": "dfe-4",
    "icon": Icons.directions_bus_outlined,
    "type": "expense",
    "name": "Transporte",
    "color": Colors.red,
  },
  {
    "uuid": "dfe-5",
    "icon": Icons.school_outlined,
    "type": "expense",
    "name": "Educación",
    "color": Colors.red,
  },
  {
    "uuid": "dfe-6",
    "icon": Icons.movie_outlined,
    "type": "expense",
    "name": "Entretenimiento",
    "color": Colors.red,
  },
  {
    "uuid": "dfe-7",
    "icon": Icons.checkroom_outlined,
    "type": "expense",
    "name": "Ropa",
    "color": Colors.red,
  },
  {
    "uuid": "dfe-8",
    "icon": Icons.pets_outlined,
    "type": "expense",
    "name": "Mascotas",
    "color": Colors.red,
  },
  {
    "uuid": "dfe-9",
    "icon": Icons.receipt_long_outlined,
    "type": "expense",
    "name": "Servicios",
    "color": Colors.red,
  },
  {
    "uuid": "dfe-10",
    "icon": Icons.redeem_outlined,
    "type": "expense",
    "name": "Regalos",
    "color": Colors.red,
  },
];

const incomeCategories = [
  {
    "uuid": "dfi-1",
    "icon": Icons.work_outline,
    "type": "income",
    "name": "Sueldo",
    "color": Colors.green,
  },
  {
    "uuid": "dfi-2",
    "icon": Icons.attach_money_outlined,
    "type": "income",
    "name": "Venta",
    "color": Colors.green,
  },
  {
    "uuid": "dfi-3",
    "icon": Icons.handshake_outlined,
    "type": "income",
    "name": "Préstamo",
    "color": Colors.green,
  },
  {
    "uuid": "dfi-4",
    "icon": Icons.trending_up_outlined,
    "type": "income",
    "name": "Inversiones",
    "color": Colors.green,
  },
  {
    "uuid": "dfi-5",
    "icon": Icons.card_giftcard_outlined,
    "type": "income",
    "name": "Regalo",
    "color": Colors.green,
  },
  {
    "uuid": "dfi-6",
    "icon": Icons.swap_horiz_outlined,
    "type": "income",
    "name": "Transferencia",
    "color": Colors.green,
  },
  {
    "uuid": "dfi-7",
    "icon": Icons.add_circle_outline,
    "type": "income",
    "name": "Otros Ingresos",
    "color": Colors.green,
  },
];
